puppycompanyblog/blog_posts/forms.py
# blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Write Your Post Here', validators=[DataRequired()])
    submit = SubmitField("Post")

puppycompanyblog/blog_posts/views.py
# blog_posts/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint
from flask_login import current_user, login_required
from werkzeug.exceptions import abort
from puppycompanyblog import db
from puppycompanyblog.models import BlogPost
from puppycompanyblog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts', __name__)

# CREATE
@blog_posts.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post = BlogPost(title=form.title.data, text=form.text.data, user_id=current_user.id)
        db.session.add(blog_post)
        db.session.commit()
        flash("Post created Successfully")
        return redirect(url_for('core.index'))
    
    return render_template('create_post.html', form=form, title="Create Post Page"), 200


# BLOG POST VIEW
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html', title=blog_post.title, date=blog_post.date, post=blog_post), 200

# UPDATE
@blog_posts.route('/<int:blog_post_id>/update', methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post.title=form.title.data
        blog_post.text=form.text.data
        db.session.commit()
        flash("Post Updated")
        return redirect(url_for('blog_posts.blog_post', blog_post_id = blog_post.id))
    
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html', title="updating", form=form)



# DELETE
@blog_posts.route('/<int:blog_post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post Deleted')
    return redirect(url_for('core.index')), 301

puppycompanyblog/users/views.py
# users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from puppycompanyblog import db
from puppycompanyblog.models import User, BlogPost
from puppycompanyblog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from puppycompanyblog.users.picture_handler import addProfilePic

users = Blueprint('users', __name__)


# registration
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        u = User(email=form.email.data, username=form.username.data, password = form.password.data)
        db.session.add(u)
        db.session.commit()
        flash('Thanks for Registration')
        return redirect(url_for('users.login')), 301

    return render_template('register.html', title="Registration", form=form), 200

# Login
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash("Login Success!")

            next = request.args.get('next')

            if next == None or not next[0] == '/':
                next = url_for('core.index')

            return redirect(next), 301

    return render_template('login.html', title="Login", form = form), 200







# Logout
@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('core.index')), 301


# upgrade users from
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        # current_user.username = form.username.data
        # db.session.commit()
        if form.picture.data:
            username = current_user.username
            pic = addProfilePic(form.picture.data, username)
            current_user.profile_image = pic
        if current_user:
            current_user.username = form.username.data
            db.session.commit()
            flash("User Account Updated!")
            return redirect(url_for('users.account')), 301
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/'+current_user.profile_image)

    return render_template('account.html', profile_image = profile_image, form=form)


#Blog post handaling Dynamic Routing
@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)



#user list of blog posts

puppycompanyblog/templates/account.html
{% extends "base.html" %}

{% block content %}

  <div class="container-fulid border my-5 p-5 text center">
    <h1>welcome to page for {{ current_user.username }}</h1>
    <img align="center" width="100px" src="{{ url_for('static', filename='profile_pics/'+current_user.profile_image) }}" alt="profile-image">
  </div>

  <div class="container">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}

        <div class="mb-3">
          {{ form.username.label(class="form-label") }} <br>
          {{ form.username(class="form-control") }}
        </div>

        <div class="mb-3">
          {{ form.email.label(class="form-label") }} <br>
          {{ form.email(class="form-control") }}
        </div>

        <div class="mb-3">
          {{ form.picture.label(class="form-label") }} <br>
          {{ form.picture(class="form-control") }}
        </div>

        <div class="mb-3">
          {{ form.submit(class="btn btn-primary") }}
        </div>

    </form>
  </div>
{% endblock %}

puppycompanyblog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    {% if title %}
      <title>{{ title }}- Puppy Blog</title>
    {% else %}
      <title>Welcome to Puppy Blog</title>
    {% endif %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('core.index') }}"> Micro Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link {% if request.endpoint=='core.index' %}active{% endif %}" aria-current="page" href="{{ url_for('core.index') }}">Home</a>
            <a class="nav-link {% if request.endpoint == 'core.info' %} active {% endif %}" href="{{ url_for('core.info') }}">about</a>
            {% if current_user.is_authenticated %}
            <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
            <a class="nav-link" href="{{ url_for('blog_posts.create_post') }}">Create Post</a>
            {% else %}
            <a class="nav-link" href="{{ url_for('users.login') }}">Log In</a>
            <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <section class="container mb-3">
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      <ul>
          {% for message in messages %}
          <li> {{ message}}</li>
          {% endfor %}
      </ul>
      {% endif %}
      {% endwith %}
    </section>
    <div class="container">

      {% block content %}
      {% endblock %}
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
   
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>


  </body>
</html>

puppycompanyblog/templates/blog_post.html
{% extends "base.html" %}

{% block content %}

<div class="container-fulid border my-5 p-5 text center">
    <h1>{{ post.title }}</h1>
    <h2>Written by: {{post.author.username}} </h2>
    <h3>Published Date: {{ post.date.strftime('%B %d %Y') }} </h3>
    <p>{{ post.text }}</p>

    {% if post.author == current_user %}
        <div>
            <a href=" {{ url_for('blog_posts.update', blog_post_id = post.id) }} ">Update</a>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#del_modal">Delete</button>
        </div>
    {% endif %}

</div>  

<div class="modal" tabindex="-1" id="del_modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id = post.id) }}" method="POST">
            <button type="submit" class="btn btn-danger">Confirm</button>
          </form>
        </div>
      </div>
    </div>
</div>




{% endblock %}

puppycompanyblog/templates/create_post.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
       <form method="POST">
            {{ form.hidden_tag() }}

            <div class="from-group">
                {{ form.title.label(class="form-control-label") }}
                {{ form.title(class="form-control form-control-lg") }}
            </div>
            
            <div class="from-group mb-3">
                {{ form.text.label(class="form-control-label") }}
                {{ form.text(class="form-control form-control-lg") }}
            </div>

            <div class="from-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>

       </form>

    </div>
{% endblock %}

puppycompanyblog/templates/index.html
{% extends "base.html" %}
{% block content %}

  <div class="container-fulid border my-5 p-5 text center">
    <h1>Puppy Company Blog</h1>
  </div>

  <div class="container">
    {% for post in blog_posts.items %}
      <div class="card">
        <div class="card-body">
          <h2><a class="card-title" href="{{ url_for('blog_posts.blog_post', blog_post_id = post.id | int) }}">{{post.title}}</a></h2>
          <a href="{{ url_for('users.user_posts', username=post.author.username)}}">Written By: {{post.author.username}} </a>
          <p>Published on: {{post.date.strftime("%y-%m-%d")}} </p>
          <a href="{{ url_for('blog_posts.blog_post', blog_post_id = post.id | int) }}" class="btn btn-primary">Read More Blog Post</a>
        </div>
      </div>
    {% endfor %}
  </div>
  <nav aria-label="Page navigation">
    <ul class="pagination">
      {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if blog_posts.page == page_num %}
        <li class="page-item disabled"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
      {% endif %}
      {% endfor %}
    </ul>
  </nav>

{% endblock %}

puppycompanyblog/templates/info.html
{% extends "base.html" %}
{% block content %}
  <div class="container-fulid border my-5 p-5">
    <h1>Info about out company</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
{% endblock %}

puppycompanyblog/templates/login.html
{% extends "base.html" %}

{% block content %}
  <form  method="POST">
    {{ form.hidden_tag() }}
    <p>
      {{ form.email.label }} <br>
      {{ form.email() }}
    </p>

    <p>
      {{ form.password.label }} <br>
      {{ form.password() }}
    </p>

    <p>
      {{ form.submit() }}
    </p>
  </form>
{% endblock %}

puppycompanyblog/templates/register.html
{% extends "base.html" %}

{% block content %}
  <form  method="POST">
    {{ form.hidden_tag() }}
    <p>
      {{ form.email.label }} <br>
      {{ form.email() }}
    </p>

    <p>
      {{ form.username.label }} <br>
      {{ form.username() }}
    </p>

    <p>
      {{ form.password.label }} <br>
      {{ form.password() }}
    </p>
    <p>
      {{ form.pass_confirm.label }} <br>
      {{ form.pass_confirm() }}
    </p>
    <p>
      {{ form.submit() }}
    </p>

  </form>
{% endblock %}

puppycompanyblog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <div class="container-fulid border my-5 p-5 text center">
      <h1>Welcome to page for {{ user.username }}</h1>
      <img src="{{ url_for('static', filename='profile_image/'+user.profile_image)}}" alt="">
    </div>
    {% for post in blog_posts.items %}
      <h1> <a href="{{ url_for('blog_posts.blog_post', blog_post_id = post.id ) }}">{{ post.title }}</a></h1>
      Writter By: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{post.author.username}}</a>
      <p class="text-muted">Published on: {{ post.date.strftime('%y %m %d') }}</p>
      <br>
      <p>{{ post.text }}</p>
      <br>
    {% endfor %}
  </div>

  <nav aria-label="Page navigation">
      <ul class="pagination">
        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if blog_posts.page == page_num %}
            <li class="page-item disabled"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
          {% endif %}
        {% endfor %}
      </ul>
  </nav>
{% endblock %}